# Generated by Django 2.2.12 on 2020-06-11 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_manager', models.CharField(max_length=200)),
                ('project_number', models.CharField(max_length=20)),
            ],
        ),
    ]
