# Generated by Django 2.2.13 on 2020-07-09 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_manager', models.CharField(max_length=200)),
                ('project_number', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=models.SET('deleted'), related_name='customer', to='customers.Customer')),
            ],
            options={
                'permissions': [('special_status', 'can_read_all_projects')],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_name', models.CharField(max_length=255)),
                ('deliverable_description', models.TextField(max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.Project')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
