# Generated by Django 2.2.13 on 2020-06-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('special_status', 'can_read_all_projects')]},
        ),
    ]
