# Generated by Django 2.2.13 on 2020-06-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200616_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('special_status', 'Can view all projects')]},
        ),
    ]
