# Generated by Django 2.2.13 on 2020-06-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200616_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('special_status', 'can_read_all_projects')]},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
