# Generated by Django 2.2.13 on 2020-07-09 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='company name')),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
            ],
        ),
    ]
